Tests runner
nbirillo/hyperstyle-analysis-prod pull request #17
Opened 2023-07-24 09:53 UTC by GirZ0n

2023-07-25 08:28 UTC, nbirillo requested changes
It looks awesome, I have only small comments. Also, you need to add tests - for the functionality, another one that just runs the scripts

2023-07-25 08:28 UTC, nbirillo commented on jba/src/jba/tests/tests_parser.py
> +def _parse_test_logs(submission_gradle_logs_path: Path) -> Optional[List[TestData]]:
I'w prefer to separate this function into several ones, also maybe it is better to move HTML parsing into another file

2023-07-25 08:28 UTC, nbirillo commented on jba/src/jba/tests/tests_parser.py
> +class TestDataField(Enum):
Could you please move models classes into Models file in this package?

2023-08-06 10:27 UTC, closed without merging

2023-08-06 10:28 UTC, GirZ0n commented
Closed due to splitting into #18 and #19